
function [mtty] = CrAMP_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = CrAMP_odeo(mttx,mttu,mttt,mttpar);
## System CrAMP, representation odeo, language m; 
## File CrAMP_odeo.m; 
## Generated by MTT on Mon Mar  2 14:54:22 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_adp 	= mttpar(1);
   k_amp 	= mttpar(2);
   k_atp 	= mttpar(3);
   k_cr 	= mttpar(4);
   k_p 	= mttpar(5);
   k_pcr 	= mttpar(6);
   rt 	= mttpar(7);
   k_adk 	= mttpar(8);
   k_ck 	= mttpar(9);
   rho_adk 	= mttpar(10);
   rho_ck 	= mttpar(11);
   v_adk 	= mttpar(12);
   v_ck 	= mttpar(13);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;
mttx6 = mttx(6) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);

## Unknown Inputs 

   mtty = zeros(2,1);

## BEGIN Code

## Code
  mtty(1) = (v_adk*( - k_adp**2*mttx1**2 + k_amp*k_atp*mttx2*mttx3))/(k_adk +  \
k_adp**2*mttx1**2*rho_adk - k_amp*k_atp*mttx2*mttx3*rho_adk + k_amp*k_atp*mttx2* \
  mttx3);
  mtty(2) = (v_ck*( - k_adp*k_pcr*mttx1*mttx6 + k_atp*k_cr*mttx3*mttx4))/(k_adp \
*k_pcr*mttx1*mttx6*rho_ck - k_atp*k_cr*mttx3*mttx4*rho_ck + k_atp*k_cr*mttx3* \
  mttx4 + k_ck);
## END Code
endfunction
