function [input_name,output_name,state_name,nonstate_name] = CrAMP_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = CrAMP_struc
%% Structure file (CrAMP_struc.m)
%% Generated by MTT at Mon Mar  2 14:54:21 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'CrAMP__ADK__v_1__u_u'
'CrAMP__CK__v_1__u_u'
];
output_name = [
'CrAMP__ADK__v_2__y_y'
'CrAMP__CK__v_2__y_y'
];
state_name = [
'CrAMP__ADP_ADP'
'CrAMP__AMP_AMP'
'CrAMP__ATP_ATP'
'CrAMP__Cr_Cr'
'CrAMP__P_P'
'CrAMP__PCr_PCr'
];
