function sympar = CrAMP_sympar();
% sympar = CrAMP_sympar();
%System CrAMP, representation sympar, language m;
%File CrAMP_sympar.m;
%Generated by MTT on Mon Mar  2 14:54:21 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_ADP 	= 1; # CrAMP
  sympar.K_AMP 	= 2; # CrAMP
  sympar.K_ATP 	= 3; # CrAMP
  sympar.K_Cr 	= 4; # CrAMP
  sympar.K_P 	= 5; # CrAMP
  sympar.K_PCr 	= 6; # CrAMP
  sympar.RT 	= 7; # CrAMP
  sympar.k_ADK 	= 8; # CrAMP
  sympar.k_CK 	= 9; # CrAMP
  sympar.rho_ADK 	= 10; # CrAMP
  sympar.rho_CK 	= 11; # CrAMP
  sympar.v_ADK 	= 12; # CrAMP
  sympar.v_CK 	= 13; # CrAMP
