
function [mttu] = CrAMP_input(mttx,mtty,mttt,mttpar);
## [mttu] = CrAMP_input(mttx,mtty,mttt,mttpar);
## System CrAMP, representation input, language m; 
## File CrAMP_input.m; 
## Generated by MTT on Mon Mar  2 14:54:22 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_adp 	= mttpar(1);
   k_amp 	= mttpar(2);
   k_atp 	= mttpar(3);
   k_cr 	= mttpar(4);
   k_p 	= mttpar(5);
   k_pcr 	= mttpar(6);
   rt 	= mttpar(7);
   k_adk 	= mttpar(8);
   k_ck 	= mttpar(9);
   rho_adk 	= mttpar(10);
   rho_ck 	= mttpar(11);
   v_adk 	= mttpar(12);
   v_ck 	= mttpar(13);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;
mttx6 = mttx(6) ;

   mttu = zeros(2,1);

## BEGIN Code

## States
  cramp__adp 	= mttx(1);
  cramp__amp 	= mttx(2);
  cramp__atp 	= mttx(3);
  cramp__cr 	= mttx(4);
  cramp__p 	= mttx(5);
  cramp__pcr 	= mttx(6);

## User defined code from CrAMP_input.txt
  cramp__adk__v_1__u	=  1.0; 
  cramp__ck__v_1__u	=  1.0; 

  ## Set up the mttu vector
  mttu(1)	= cramp__adk__v_1__u;
  mttu(2)	= cramp__ck__v_1__u;
## END Code
endfunction
