function [input_name,output_name,state_name,nonstate_name] = FBP2GAP_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = FBP2GAP_struc
%% Structure file (FBP2GAP_struc.m)
%% Generated by MTT at Mon Mar  2 14:53:19 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'FBP2GAP__ALD__v_1__u_u'
'FBP2GAP__TPI__v_1__u_u'
];
output_name = [
'FBP2GAP__ALD__v_2__y_y'
'FBP2GAP__TPI__v_2__y_y'
];
state_name = [
'FBP2GAP__DHAP_DHAP'
'FBP2GAP__FBP_FBP'
'FBP2GAP__GAP_GAP'
];
