function sympar = FBP2GAP_sympar();
% sympar = FBP2GAP_sympar();
%System FBP2GAP, representation sympar, language m;
%File FBP2GAP_sympar.m;
%Generated by MTT on Mon Mar  2 14:53:19 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_DHAP 	= 1; # FBP2GAP
  sympar.K_FBP 	= 2; # FBP2GAP
  sympar.K_GAP 	= 3; # FBP2GAP
  sympar.RT 	= 4; # FBP2GAP
  sympar.k_ALD 	= 5; # FBP2GAP
  sympar.k_TPI 	= 6; # FBP2GAP
  sympar.rho_ALD 	= 7; # FBP2GAP
  sympar.rho_TPI 	= 8; # FBP2GAP
  sympar.v_ALD 	= 9; # FBP2GAP
  sympar.v_TPI 	= 10; # FBP2GAP
