
function [mtty] = FBP2GAP_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = FBP2GAP_odeo(mttx,mttu,mttt,mttpar);
## System FBP2GAP, representation odeo, language m; 
## File FBP2GAP_odeo.m; 
## Generated by MTT on Mon Mar  2 14:53:20 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_dhap 	= mttpar(1);
   k_fbp 	= mttpar(2);
   k_gap 	= mttpar(3);
   rt 	= mttpar(4);
   k_ald 	= mttpar(5);
   k_tpi 	= mttpar(6);
   rho_ald 	= mttpar(7);
   rho_tpi 	= mttpar(8);
   v_ald 	= mttpar(9);
   v_tpi 	= mttpar(10);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);

## Unknown Inputs 

   mtty = zeros(2,1);

## BEGIN Code

## Code
  mtty(1) = (v_ald*( - k_dhap*k_gap*mttx1*mttx3 + k_fbp*mttx2))/(k_ald + k_dhap \
*k_gap*mttx1*mttx3*rho_ald - k_fbp*mttx2*rho_ald + k_fbp*mttx2);
  mtty(2) = (v_tpi*( - k_dhap*mttx1 + k_gap*mttx3))/(k_dhap*mttx1*rho_tpi -  \
k_gap*mttx3*rho_tpi + k_gap*mttx3 + k_tpi);
## END Code
endfunction
