
function [mtta,mttb,mttc,mttd,mtte] = GAP2LAC_dm(mttpar,mttx);
## [mtta,mttb,mttc,mttd,mtte] = GAP2LAC_dm(mttpar,mttx);
## System GAP2LAC, representation dm, language m; 
## File GAP2LAC_dm.m; 
## Generated by MTT on Mon Mar  2 14:53:52 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_dpg 	= mttpar(1);
   k_lac 	= mttpar(2);
   k_laco 	= mttpar(3);
   k_nad 	= mttpar(4);
   k_nadh 	= mttpar(5);
   k_p2g 	= mttpar(6);
   k_p3g 	= mttpar(7);
   k_pep 	= mttpar(8);
   k_pyr 	= mttpar(9);
   rt 	= mttpar(10);
   k_eno 	= mttpar(11);
   k_fout 	= mttpar(12);
   k_gapdh 	= mttpar(13);
   k_ldh 	= mttpar(14);
   k_pgk 	= mttpar(15);
   k_pgm 	= mttpar(16);
   k_pk 	= mttpar(17);
   rho_eno 	= mttpar(18);
   rho_fout 	= mttpar(19);
   rho_gapdh 	= mttpar(20);
   rho_ldh 	= mttpar(21);
   rho_pgk 	= mttpar(22);
   rho_pgm 	= mttpar(23);
   rho_pk 	= mttpar(24);
   v_eno 	= mttpar(25);
   v_fout 	= mttpar(26);
   v_gapdh 	= mttpar(27);
   v_ldh 	= mttpar(28);
   v_pgk 	= mttpar(29);
   v_pgm 	= mttpar(30);
   v_pk 	= mttpar(31);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;
mttx6 = mttx(6) ;
mttx7 = mttx(7) ;
mttx8 = mttx(8) ;
mttx9 = mttx(9) ;

   mtta = zeros(9,9);
   mttb = zeros(9,7);
   mttc = zeros(7,9);
   mttd = zeros(7,7);
   mtte = zeros(9,9);

## BEGIN Code

## Code
  mtte(1,1) = 1;
  mtte(2,2) = 1;
  mtte(3,3) = 1;
  mtte(4,4) = 1;
  mtte(5,5) = 1;
  mtte(6,6) = 1;
  mtte(7,7) = 1;
  mtte(8,8) = 1;
  mtte(9,9) = 1;
  mttb(1,4) = 1;
  mttb(1,6) = -1;
  mttb(2,2) = -1;
  mttb(2,5) = 1;
  mttb(3,2) = 1;
  mttb(4,4) = -1;
  mttb(4,5) = 1;
  mttb(5,4) = 1;
  mttb(5,5) = -1;
  mttb(6,1) = -1;
  mttb(6,3) = 1;
  mttb(7,3) = -1;
  mttb(7,6) = 1;
  mttb(8,1) = 1;
  mttb(8,7) = -1;
  mttb(9,5) = -1;
  mttb(9,7) = 1;
  mttc(1,6) = (k_p2g*v_eno)/k_eno;
  mttc(1,8) = ( - k_pep*v_eno)/k_eno;
  mttc(2,2) = (k_lac*v_fout)/k_fout;
  mttc(2,3) = ( - k_laco*v_fout)/k_fout;
  mttc(3,6) = ( - k_p2g*v_pgm)/k_pgm;
  mttc(3,7) = (k_p3g*v_pgm)/k_pgm;
  mttc(4,4) = (k_nad*v_gapdh)/k_gapdh;
  mttc(6,1) = (k_dpg*v_pgk)/k_pgk;
  mttc(6,7) = ( - k_p3g*v_pgk)/k_pgk;
  mttc(7,8) = (k_pep*v_pk)/k_pk;
  mttc(7,9) = ( - k_pyr*v_pk)/k_pk;
## END Code
endfunction
