function [input_name,output_name,state_name,nonstate_name] = GAP2LAC_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = GAP2LAC_struc
%% Structure file (GAP2LAC_struc.m)
%% Generated by MTT at Mon Mar  2 14:53:53 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'GAP2LAC__ENO__v_1__u_u'
'GAP2LAC__Fout__v_1__u_u'
'GAP2LAC__PGM__v_1__u_u'
'GAP2LAC__GAPDH__Re__v_1__u_u'
'GAP2LAC__LDH__Re__v_1__u_u'
'GAP2LAC__PGK__Re__v_1__u_u'
'GAP2LAC__PK__Re__v_1__u_u'
];
output_name = [
'GAP2LAC__ENO__v_2__y_y'
'GAP2LAC__Fout__v_2__y_y'
'GAP2LAC__PGM__v_2__y_y'
'GAP2LAC__GAPDH__Re__v_2__y_y'
'GAP2LAC__LDH__Re__v_2__y_y'
'GAP2LAC__PGK__Re__v_2__y_y'
'GAP2LAC__PK__Re__v_2__y_y'
];
state_name = [
'GAP2LAC__DPG_DPG'
'GAP2LAC__LAC_LAC'
'GAP2LAC__LACo_LACo'
'GAP2LAC__NAD_NAD'
'GAP2LAC__NADH_NADH'
'GAP2LAC__P2G_P2G'
'GAP2LAC__P3G_P3G'
'GAP2LAC__PEP_PEP'
'GAP2LAC__PYR_PYR'
];
