
function [mttu] = GAP2LAC_input(mttx,mtty,mttt,mttpar);
## [mttu] = GAP2LAC_input(mttx,mtty,mttt,mttpar);
## System GAP2LAC, representation input, language m; 
## File GAP2LAC_input.m; 
## Generated by MTT on Mon Mar  2 14:53:53 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_dpg 	= mttpar(1);
   k_lac 	= mttpar(2);
   k_laco 	= mttpar(3);
   k_nad 	= mttpar(4);
   k_nadh 	= mttpar(5);
   k_p2g 	= mttpar(6);
   k_p3g 	= mttpar(7);
   k_pep 	= mttpar(8);
   k_pyr 	= mttpar(9);
   rt 	= mttpar(10);
   k_eno 	= mttpar(11);
   k_fout 	= mttpar(12);
   k_gapdh 	= mttpar(13);
   k_ldh 	= mttpar(14);
   k_pgk 	= mttpar(15);
   k_pgm 	= mttpar(16);
   k_pk 	= mttpar(17);
   rho_eno 	= mttpar(18);
   rho_fout 	= mttpar(19);
   rho_gapdh 	= mttpar(20);
   rho_ldh 	= mttpar(21);
   rho_pgk 	= mttpar(22);
   rho_pgm 	= mttpar(23);
   rho_pk 	= mttpar(24);
   v_eno 	= mttpar(25);
   v_fout 	= mttpar(26);
   v_gapdh 	= mttpar(27);
   v_ldh 	= mttpar(28);
   v_pgk 	= mttpar(29);
   v_pgm 	= mttpar(30);
   v_pk 	= mttpar(31);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;
mttx6 = mttx(6) ;
mttx7 = mttx(7) ;
mttx8 = mttx(8) ;
mttx9 = mttx(9) ;

   mttu = zeros(7,1);

## BEGIN Code

## States
  gap2lac__dpg 	= mttx(1);
  gap2lac__lac 	= mttx(2);
  gap2lac__laco 	= mttx(3);
  gap2lac__nad 	= mttx(4);
  gap2lac__nadh 	= mttx(5);
  gap2lac__p2g 	= mttx(6);
  gap2lac__p3g 	= mttx(7);
  gap2lac__pep 	= mttx(8);
  gap2lac__pyr 	= mttx(9);

## User defined code from GAP2LAC_input.txt
  gap2lac__eno__v_1__u	=  1.0; 
  gap2lac__fout__v_1__u	=  1.0; 
  gap2lac__gapdh__re__v_1__u	=  1.0; 
  gap2lac__ldh__re__v_1__u	=  1.0; 
  gap2lac__pgk__re__v_1__u	=  1.0; 
  gap2lac__pgm__v_1__u	=  1.0; 
  gap2lac__pk__re__v_1__u	=  1.0; 

  ## Set up the mttu vector
  mttu(1)	= gap2lac__eno__v_1__u;
  mttu(2)	= gap2lac__fout__v_1__u;
  mttu(3)	= gap2lac__pgm__v_1__u;
  mttu(4)	= gap2lac__gapdh__re__v_1__u;
  mttu(5)	= gap2lac__ldh__re__v_1__u;
  mttu(6)	= gap2lac__pgk__re__v_1__u;
  mttu(7)	= gap2lac__pk__re__v_1__u;
## END Code
endfunction
