function sympar = GAP2LAC_sympar();
% sympar = GAP2LAC_sympar();
%System GAP2LAC, representation sympar, language m;
%File GAP2LAC_sympar.m;
%Generated by MTT on Mon Mar  2 14:53:53 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_DPG 	= 1; # GAP2LAC
  sympar.K_LAC 	= 2; # GAP2LAC
  sympar.K_LACo 	= 3; # GAP2LAC
  sympar.K_NAD 	= 4; # GAP2LAC
  sympar.K_NADH 	= 5; # GAP2LAC
  sympar.K_P2G 	= 6; # GAP2LAC
  sympar.K_P3G 	= 7; # GAP2LAC
  sympar.K_PEP 	= 8; # GAP2LAC
  sympar.K_PYR 	= 9; # GAP2LAC
  sympar.RT 	= 10; # GAP2LAC
  sympar.k_ENO 	= 11; # GAP2LAC
  sympar.k_Fout 	= 12; # GAP2LAC
  sympar.k_GAPDH 	= 13; # GAP2LAC
  sympar.k_LDH 	= 14; # GAP2LAC
  sympar.k_PGK 	= 15; # GAP2LAC
  sympar.k_PGM 	= 16; # GAP2LAC
  sympar.k_PK 	= 17; # GAP2LAC
  sympar.rho_ENO 	= 18; # GAP2LAC
  sympar.rho_Fout 	= 19; # GAP2LAC
  sympar.rho_GAPDH 	= 20; # GAP2LAC
  sympar.rho_LDH 	= 21; # GAP2LAC
  sympar.rho_PGK 	= 22; # GAP2LAC
  sympar.rho_PGM 	= 23; # GAP2LAC
  sympar.rho_PK 	= 24; # GAP2LAC
  sympar.v_ENO 	= 25; # GAP2LAC
  sympar.v_Fout 	= 26; # GAP2LAC
  sympar.v_GAPDH 	= 27; # GAP2LAC
  sympar.v_LDH 	= 28; # GAP2LAC
  sympar.v_PGK 	= 29; # GAP2LAC
  sympar.v_PGM 	= 30; # GAP2LAC
  sympar.v_PK 	= 31; # GAP2LAC
