
function [mtta,mttb,mttc,mttd,mtte] = GLY2FBP_dm(mttpar,mttx);
## [mtta,mttb,mttc,mttd,mtte] = GLY2FBP_dm(mttpar,mttx);
## System GLY2FBP, representation dm, language m; 
## File GLY2FBP_dm.m; 
## Generated by MTT on Mon Mar  2 14:52:52 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_f6p 	= mttpar(1);
   k_g1p 	= mttpar(2);
   k_g6p 	= mttpar(3);
   k_gly 	= mttpar(4);
   rt 	= mttpar(5);
   k_gpa 	= mttpar(6);
   k_gpb 	= mttpar(7);
   k_pfk 	= mttpar(8);
   k_pgi 	= mttpar(9);
   k_pglm 	= mttpar(10);
   rho_gpa 	= mttpar(11);
   rho_gpb 	= mttpar(12);
   rho_pfk 	= mttpar(13);
   rho_pgi 	= mttpar(14);
   rho_pglm 	= mttpar(15);
   v_gpa 	= mttpar(16);
   v_gpb 	= mttpar(17);
   v_pfk 	= mttpar(18);
   v_pgi 	= mttpar(19);
   v_pglm 	= mttpar(20);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;

   mtta = zeros(4,4);
   mttb = zeros(4,5);
   mttc = zeros(5,4);
   mttd = zeros(5,5);
   mtte = zeros(4,4);

## BEGIN Code

## Code
  mtte(1,1) = 1;
  mtte(2,2) = 1;
  mtte(3,3) = 1;
  mtte(4,4) = 1;
  mttb(1,3) = 1;
  mttb(1,5) = -1;
  mttb(2,1) = 1;
  mttb(2,2) = 1;
  mttb(2,4) = -1;
  mttb(3,3) = -1;
  mttb(3,4) = 1;
  mttc(1,4) = (k_gly*v_gpa)/k_gpa;
  mttc(2,4) = (k_gly*v_gpb)/k_gpb;
  mttc(3,1) = ( - k_f6p*v_pgi)/k_pgi;
  mttc(3,3) = (k_g6p*v_pgi)/k_pgi;
  mttc(4,2) = (k_g1p*v_pglm)/k_pglm;
  mttc(4,3) = ( - k_g6p*v_pglm)/k_pglm;
  mttc(5,1) = (k_f6p*v_pfk*(k_pfk + 1))/(k_pfk**2 + 2*k_pfk*rho_pfk + rho_pfk**2);
## END Code
endfunction
