function [input_name,output_name,state_name,nonstate_name] = GLY2FBP_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = GLY2FBP_struc
%% Structure file (GLY2FBP_struc.m)
%% Generated by MTT at Mon Mar  2 14:52:53 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'GLY2FBP__GP__GPa__v_1__u_u'
'GLY2FBP__GP__GPb__v_1__u_u'
'GLY2FBP__PGI__v_1__u_u'
'GLY2FBP__PGLM__v_1__u_u'
'GLY2FBP__PFK__Re__v_1__u_u'
];
output_name = [
'GLY2FBP__GP__GPa__v_2__y_y'
'GLY2FBP__GP__GPb__v_2__y_y'
'GLY2FBP__PGI__v_2__y_y'
'GLY2FBP__PGLM__v_2__y_y'
'GLY2FBP__PFK__Re__v_2__y_y'
];
state_name = [
'GLY2FBP__F6P_F6P'
'GLY2FBP__G1P_G1P'
'GLY2FBP__G6P_G6P'
'GLY2FBP__GLY_GLY'
];
