
function [mttu] = GLY2FBP_input(mttx,mtty,mttt,mttpar);
## [mttu] = GLY2FBP_input(mttx,mtty,mttt,mttpar);
## System GLY2FBP, representation input, language m; 
## File GLY2FBP_input.m; 
## Generated by MTT on Mon Mar  2 14:52:53 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_f6p 	= mttpar(1);
   k_g1p 	= mttpar(2);
   k_g6p 	= mttpar(3);
   k_gly 	= mttpar(4);
   rt 	= mttpar(5);
   k_gpa 	= mttpar(6);
   k_gpb 	= mttpar(7);
   k_pfk 	= mttpar(8);
   k_pgi 	= mttpar(9);
   k_pglm 	= mttpar(10);
   rho_gpa 	= mttpar(11);
   rho_gpb 	= mttpar(12);
   rho_pfk 	= mttpar(13);
   rho_pgi 	= mttpar(14);
   rho_pglm 	= mttpar(15);
   v_gpa 	= mttpar(16);
   v_gpb 	= mttpar(17);
   v_pfk 	= mttpar(18);
   v_pgi 	= mttpar(19);
   v_pglm 	= mttpar(20);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;

   mttu = zeros(5,1);

## BEGIN Code

## States
  gly2fbp__f6p 	= mttx(1);
  gly2fbp__g1p 	= mttx(2);
  gly2fbp__g6p 	= mttx(3);
  gly2fbp__gly 	= mttx(4);

## User defined code from GLY2FBP_input.txt
  gly2fbp__gp__gpa__v_1__u	=  1.0; 
  gly2fbp__gp__gpb__v_1__u	=  1.0; 
  gly2fbp__pfk__re__v_1__u	=  1.0; 
  gly2fbp__pgi__v_1__u	=  1.0; 
  gly2fbp__pglm__v_1__u	=  1.0; 

  ## Set up the mttu vector
  mttu(1)	= gly2fbp__gp__gpa__v_1__u;
  mttu(2)	= gly2fbp__gp__gpb__v_1__u;
  mttu(3)	= gly2fbp__pgi__v_1__u;
  mttu(4)	= gly2fbp__pglm__v_1__u;
  mttu(5)	= gly2fbp__pfk__re__v_1__u;
## END Code
endfunction
