
function [mtty] = GLY2FBP_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = GLY2FBP_odeo(mttx,mttu,mttt,mttpar);
## System GLY2FBP, representation odeo, language m; 
## File GLY2FBP_odeo.m; 
## Generated by MTT on Mon Mar  2 14:52:53 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_f6p 	= mttpar(1);
   k_g1p 	= mttpar(2);
   k_g6p 	= mttpar(3);
   k_gly 	= mttpar(4);
   rt 	= mttpar(5);
   k_gpa 	= mttpar(6);
   k_gpb 	= mttpar(7);
   k_pfk 	= mttpar(8);
   k_pgi 	= mttpar(9);
   k_pglm 	= mttpar(10);
   rho_gpa 	= mttpar(11);
   rho_gpb 	= mttpar(12);
   rho_pfk 	= mttpar(13);
   rho_pgi 	= mttpar(14);
   rho_pglm 	= mttpar(15);
   v_gpa 	= mttpar(16);
   v_gpb 	= mttpar(17);
   v_pfk 	= mttpar(18);
   v_pgi 	= mttpar(19);
   v_pglm 	= mttpar(20);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);
mttu4 = mttu(4);
mttu5 = mttu(5);

## Unknown Inputs 

   mtty = zeros(5,1);

## BEGIN Code

## Code
  mtty(1) = (k_gly*mttx4*v_gpa*( - k_g1p*mttx2 + 1))/(k_g1p*k_gly*mttx2*mttx4* \
rho_gpa - k_gly*mttx4*rho_gpa + k_gly*mttx4 + k_gpa);
  mtty(2) = (k_gly*mttx4*v_gpb*( - k_g1p*mttx2 + 1))/(k_g1p*k_gly*mttx2*mttx4* \
rho_gpb - k_gly*mttx4*rho_gpb + k_gly*mttx4 + k_gpb);
  mtty(3) = (v_pgi*( - k_f6p*mttx1 + k_g6p*mttx3))/(k_f6p*mttx1*rho_pgi - k_g6p \
*mttx3*rho_pgi + k_g6p*mttx3 + k_pgi);
  mtty(4) = (v_pglm*( - k_g1p*mttx2 + k_g6p*mttx3))/(k_g1p*mttx2*rho_pglm -  \
k_g1p*mttx2 - k_g6p*mttx3*rho_pglm - k_pglm);
  mtty(5) = (v_pfk*( - k_f6p*mttx1 + 1))/(k_f6p*mttx1*rho_pfk - k_f6p*mttx1 -  \
k_pfk - rho_pfk);
## END Code
endfunction
