function sympar = GLY2LAC_sympar();
% sympar = GLY2LAC_sympar();
%System GLY2LAC, representation sympar, language m;
%File GLY2LAC_sympar.m;
%Generated by MTT on Mon Mar  2 14:54:58 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_DHAP 	= 1; # GLY2LAC__mttFBP2GAP
  sympar.K_DPG 	= 2; # GLY2LAC__mttGAP2LAC
  sympar.K_F6P 	= 3; # GLY2LAC__mttGLY2FBP
  sympar.K_FBP 	= 4; # GLY2LAC__mttFBP2GAP
  sympar.K_G1P 	= 5; # GLY2LAC__mttGLY2FBP
  sympar.K_G6P 	= 6; # GLY2LAC__mttGLY2FBP
  sympar.K_GAP 	= 7; # GLY2LAC__mttFBP2GAP
  sympar.K_GLY 	= 8; # GLY2LAC__mttGLY2FBP
  sympar.K_LAC 	= 9; # GLY2LAC__mttGAP2LAC
  sympar.K_LACo 	= 10; # GLY2LAC__mttGAP2LAC
  sympar.K_NAD 	= 11; # GLY2LAC__mttGAP2LAC
  sympar.K_NADH 	= 12; # GLY2LAC__mttGAP2LAC
  sympar.K_P2G 	= 13; # GLY2LAC__mttGAP2LAC
  sympar.K_P3G 	= 14; # GLY2LAC__mttGAP2LAC
  sympar.K_PEP 	= 15; # GLY2LAC__mttGAP2LAC
  sympar.K_PYR 	= 16; # GLY2LAC__mttGAP2LAC
  sympar.RT 	= 17; # GLY2LAC__mttGAP2LAC,GLY2LAC__mttGLY2FBP,
  sympar.k_ALD 	= 18; # GLY2LAC__mttFBP2GAP
  sympar.k_ENO 	= 19; # GLY2LAC__mttGAP2LAC
  sympar.k_Fout 	= 20; # GLY2LAC__mttGAP2LAC
  sympar.k_GAPDH 	= 21; # GLY2LAC__mttGAP2LAC
  sympar.k_GPa 	= 22; # GLY2LAC__mttGLY2FBP__GP
  sympar.k_GPb 	= 23; # GLY2LAC__mttGLY2FBP__GP
  sympar.k_LDH 	= 24; # GLY2LAC__mttGAP2LAC
  sympar.k_PFK 	= 25; # GLY2LAC__mttGLY2FBP
  sympar.k_PGI 	= 26; # GLY2LAC__mttGLY2FBP
  sympar.k_PGK 	= 27; # GLY2LAC__mttGAP2LAC
  sympar.k_PGLM 	= 28; # GLY2LAC__mttGLY2FBP
  sympar.k_PGM 	= 29; # GLY2LAC__mttGAP2LAC
  sympar.k_PK 	= 30; # GLY2LAC__mttGAP2LAC
  sympar.k_TPI 	= 31; # GLY2LAC__mttFBP2GAP
  sympar.rho_ALD 	= 32; # GLY2LAC__mttFBP2GAP
  sympar.rho_ENO 	= 33; # GLY2LAC__mttGAP2LAC
  sympar.rho_Fout 	= 34; # GLY2LAC__mttGAP2LAC
  sympar.rho_GAPDH 	= 35; # GLY2LAC__mttGAP2LAC
  sympar.rho_GPa 	= 36; # GLY2LAC__mttGLY2FBP__GP
  sympar.rho_GPb 	= 37; # GLY2LAC__mttGLY2FBP__GP
  sympar.rho_LDH 	= 38; # GLY2LAC__mttGAP2LAC
  sympar.rho_PFK 	= 39; # GLY2LAC__mttGLY2FBP
  sympar.rho_PGI 	= 40; # GLY2LAC__mttGLY2FBP
  sympar.rho_PGK 	= 41; # GLY2LAC__mttGAP2LAC
  sympar.rho_PGLM 	= 42; # GLY2LAC__mttGLY2FBP
  sympar.rho_PGM 	= 43; # GLY2LAC__mttGAP2LAC
  sympar.rho_PK 	= 44; # GLY2LAC__mttGAP2LAC
  sympar.rho_TPI 	= 45; # GLY2LAC__mttFBP2GAP
  sympar.v_ALD 	= 46; # GLY2LAC__mttFBP2GAP
  sympar.v_ENO 	= 47; # GLY2LAC__mttGAP2LAC
  sympar.v_Fout 	= 48; # GLY2LAC__mttGAP2LAC
  sympar.v_GAPDH 	= 49; # GLY2LAC__mttGAP2LAC
  sympar.v_GPa 	= 50; # GLY2LAC__mttGLY2FBP__GP
  sympar.v_GPb 	= 51; # GLY2LAC__mttGLY2FBP__GP
  sympar.v_LDH 	= 52; # GLY2LAC__mttGAP2LAC
  sympar.v_PFK 	= 53; # GLY2LAC__mttGLY2FBP
  sympar.v_PGI 	= 54; # GLY2LAC__mttGLY2FBP
  sympar.v_PGK 	= 55; # GLY2LAC__mttGAP2LAC
  sympar.v_PGLM 	= 56; # GLY2LAC__mttGLY2FBP
  sympar.v_PGM 	= 57; # GLY2LAC__mttGAP2LAC
  sympar.v_PK 	= 58; # GLY2LAC__mttGAP2LAC
  sympar.v_TPI 	= 59; # GLY2LAC__mttFBP2GAP
