function sympar = GLY2FBP_sympar();
% sympar = GLY2FBP_sympar();
%System GLY2FBP, representation sympar, language m;
%File GLY2FBP_sympar.m;
%Generated by MTT on Mon Mar  2 14:52:53 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_F6P 	= 1; # GLY2FBP
  sympar.K_G1P 	= 2; # GLY2FBP
  sympar.K_G6P 	= 3; # GLY2FBP
  sympar.K_GLY 	= 4; # GLY2FBP
  sympar.RT 	= 5; # GLY2FBP
  sympar.k_GPa 	= 6; # GLY2FBP__GP
  sympar.k_GPb 	= 7; # GLY2FBP__GP
  sympar.k_PFK 	= 8; # GLY2FBP
  sympar.k_PGI 	= 9; # GLY2FBP
  sympar.k_PGLM 	= 10; # GLY2FBP
  sympar.rho_GPa 	= 11; # GLY2FBP__GP
  sympar.rho_GPb 	= 12; # GLY2FBP__GP
  sympar.rho_PFK 	= 13; # GLY2FBP
  sympar.rho_PGI 	= 14; # GLY2FBP
  sympar.rho_PGLM 	= 15; # GLY2FBP
  sympar.v_GPa 	= 16; # GLY2FBP__GP
  sympar.v_GPb 	= 17; # GLY2FBP__GP
  sympar.v_PFK 	= 18; # GLY2FBP
  sympar.v_PGI 	= 19; # GLY2FBP
  sympar.v_PGLM 	= 20; # GLY2FBP
