
function [mttpar] = GLY2LAC_numpar;
## [mttpar] = GLY2LAC_numpar;
## System GLY2LAC, representation numpar, language m; 
## File GLY2LAC_numpar.m; 
## Generated by MTT on Mon Mar  2 14:54:58 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(59,1);

## BEGIN Code

## User defined code from GLY2LAC_numpar.txt
  k_dhap	=  1.0; 
  k_dpg	=  1.0; 
  k_f6p	=  1.0; 
  k_fbp	=  1.0; 
  k_g1p	=  1.0; 
  k_g6p	=  1.0; 
  k_gap	=  1.0; 
  k_gly	=  1.0; 
  k_lac	=  1.0; 
  k_laco	=  1.0; 
  k_nad	=  1.0; 
  k_nadh	=  1.0; 
  k_p2g	=  1.0; 
  k_p3g	=  1.0; 
  k_pep	=  1.0; 
  k_pyr	=  1.0; 
  rt	=  1.0; 
  k_ald	=  1.0; 
  k_eno	=  1.0; 
  k_fout	=  1.0; 
  k_gapdh	=  1.0; 
  k_gpa	=  1.0; 
  k_gpb	=  1.0; 
  k_ldh	=  1.0; 
  k_pfk	=  1.0; 
  k_pgi	=  1.0; 
  k_pgk	=  1.0; 
  k_pglm	=  1.0; 
  k_pgm	=  1.0; 
  k_pk	=  1.0; 
  k_tpi	=  1.0; 
  rho_ald	=  1.0; 
  rho_eno	=  1.0; 
  rho_fout	=  1.0; 
  rho_gapdh	=  1.0; 
  rho_gpa	=  1.0; 
  rho_gpb	=  1.0; 
  rho_ldh	=  1.0; 
  rho_pfk	=  1.0; 
  rho_pgi	=  1.0; 
  rho_pgk	=  1.0; 
  rho_pglm	=  1.0; 
  rho_pgm	=  1.0; 
  rho_pk	=  1.0; 
  rho_tpi	=  1.0; 
  v_ald	=  1.0; 
  v_eno	=  1.0; 
  v_fout	=  1.0; 
  v_gapdh	=  1.0; 
  v_gpa	=  1.0; 
  v_gpb	=  1.0; 
  v_ldh	=  1.0; 
  v_pfk	=  1.0; 
  v_pgi	=  1.0; 
  v_pgk	=  1.0; 
  v_pglm	=  1.0; 
  v_pgm	=  1.0; 
  v_pk	=  1.0; 
  v_tpi	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_dhap;
  mttpar(2)	= k_dpg;
  mttpar(3)	= k_f6p;
  mttpar(4)	= k_fbp;
  mttpar(5)	= k_g1p;
  mttpar(6)	= k_g6p;
  mttpar(7)	= k_gap;
  mttpar(8)	= k_gly;
  mttpar(9)	= k_lac;
  mttpar(10)	= k_laco;
  mttpar(11)	= k_nad;
  mttpar(12)	= k_nadh;
  mttpar(13)	= k_p2g;
  mttpar(14)	= k_p3g;
  mttpar(15)	= k_pep;
  mttpar(16)	= k_pyr;
  mttpar(17)	= rt;
  mttpar(18)	= k_ald;
  mttpar(19)	= k_eno;
  mttpar(20)	= k_fout;
  mttpar(21)	= k_gapdh;
  mttpar(22)	= k_gpa;
  mttpar(23)	= k_gpb;
  mttpar(24)	= k_ldh;
  mttpar(25)	= k_pfk;
  mttpar(26)	= k_pgi;
  mttpar(27)	= k_pgk;
  mttpar(28)	= k_pglm;
  mttpar(29)	= k_pgm;
  mttpar(30)	= k_pk;
  mttpar(31)	= k_tpi;
  mttpar(32)	= rho_ald;
  mttpar(33)	= rho_eno;
  mttpar(34)	= rho_fout;
  mttpar(35)	= rho_gapdh;
  mttpar(36)	= rho_gpa;
  mttpar(37)	= rho_gpb;
  mttpar(38)	= rho_ldh;
  mttpar(39)	= rho_pfk;
  mttpar(40)	= rho_pgi;
  mttpar(41)	= rho_pgk;
  mttpar(42)	= rho_pglm;
  mttpar(43)	= rho_pgm;
  mttpar(44)	= rho_pk;
  mttpar(45)	= rho_tpi;
  mttpar(46)	= v_ald;
  mttpar(47)	= v_eno;
  mttpar(48)	= v_fout;
  mttpar(49)	= v_gapdh;
  mttpar(50)	= v_gpa;
  mttpar(51)	= v_gpb;
  mttpar(52)	= v_ldh;
  mttpar(53)	= v_pfk;
  mttpar(54)	= v_pgi;
  mttpar(55)	= v_pgk;
  mttpar(56)	= v_pglm;
  mttpar(57)	= v_pgm;
  mttpar(58)	= v_pk;
  mttpar(59)	= v_tpi;
## END Code
endfunction
