
function [mttpar] = GLY_numpar;
## [mttpar] = GLY_numpar;
## System GLY, representation numpar, language m; 
## File GLY_numpar.m; 
## Generated by MTT on Wed Jan 14 13:56:39 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(18,1);

## BEGIN Code

## User defined code from GLY_numpar.txt
  k_f6p	=  1.0; 
  k_g1p	=  1.0; 
  k_g6p	=  1.0; 
  k_glyf	=  1.0; 
  k_glyr	=  1.0; 
  rt	=  1.0; 
  k_gpa	=  1.0; 
  k_gpb	=  1.0; 
  k_pgi	=  1.0; 
  k_pglm	=  1.0; 
  rho_gpa	=  1.0; 
  rho_gpb	=  1.0; 
  rho_pgi	=  1.0; 
  rho_pglm	=  1.0; 
  v_gpa	=  1.0; 
  v_gpb	=  1.0; 
  v_pgi	=  1.0; 
  v_pglm	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_f6p;
  mttpar(2)	= k_g1p;
  mttpar(3)	= k_g6p;
  mttpar(4)	= k_glyf;
  mttpar(5)	= k_glyr;
  mttpar(6)	= rt;
  mttpar(7)	= k_gpa;
  mttpar(8)	= k_gpb;
  mttpar(9)	= k_pgi;
  mttpar(10)	= k_pglm;
  mttpar(11)	= rho_gpa;
  mttpar(12)	= rho_gpb;
  mttpar(13)	= rho_pgi;
  mttpar(14)	= rho_pglm;
  mttpar(15)	= v_gpa;
  mttpar(16)	= v_gpb;
  mttpar(17)	= v_pgi;
  mttpar(18)	= v_pglm;
## END Code
endfunction
