
function [mtty] = GLY_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = GLY_odeo(mttx,mttu,mttt,mttpar);
## System GLY, representation odeo, language m; 
## File GLY_odeo.m; 
## Generated by MTT on Wed Jan 14 13:56:40 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_f6p 	= mttpar(1);
   k_g1p 	= mttpar(2);
   k_g6p 	= mttpar(3);
   k_glyf 	= mttpar(4);
   k_glyr 	= mttpar(5);
   rt 	= mttpar(6);
   k_gpa 	= mttpar(7);
   k_gpb 	= mttpar(8);
   k_pgi 	= mttpar(9);
   k_pglm 	= mttpar(10);
   rho_gpa 	= mttpar(11);
   rho_gpb 	= mttpar(12);
   rho_pgi 	= mttpar(13);
   rho_pglm 	= mttpar(14);
   v_gpa 	= mttpar(15);
   v_gpb 	= mttpar(16);
   v_pgi 	= mttpar(17);
   v_pglm 	= mttpar(18);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);
mttu4 = mttu(4);

## Unknown Inputs 

   mtty = zeros(4,1);

## BEGIN Code

## Code
  mtty(1) = (v_gpa*( - k_g1p*k_glyr*mttx2*mttx5 + k_glyf*mttx4))/(k_g1p*k_glyr* \
  mttx2*mttx5*rho_gpa - k_glyf*mttx4*rho_gpa + k_glyf*mttx4 + k_gpa);
  mtty(2) = (v_gpb*( - k_g1p*k_glyr*mttx2*mttx5 + k_glyf*mttx4))/(k_g1p*k_glyr* \
  mttx2*mttx5*rho_gpb - k_glyf*mttx4*rho_gpb + k_glyf*mttx4 + k_gpb);
  mtty(3) = (v_pgi*( - k_f6p*mttx1 + k_g6p*mttx3))/(k_f6p*mttx1*rho_pgi - k_g6p \
*mttx3*rho_pgi + k_g6p*mttx3 + k_pgi);
  mtty(4) = (v_pglm*( - k_g1p*mttx2 + k_g6p*mttx3))/(k_g1p*mttx2*rho_pglm -  \
k_g1p*mttx2 - k_g6p*mttx3*rho_pglm - k_pglm);
## END Code
endfunction
