
function [mttpar] = iCrAMP_numpar;
## [mttpar] = iCrAMP_numpar;
## System iCrAMP, representation numpar, language m; 
## File iCrAMP_numpar.m; 
## Generated by MTT on Thu Jan 29 13:18:43 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(13,1);

## BEGIN Code

## User defined code from iCrAMP_numpar.txt
  k_adp	=  1.0; 
  k_amp	=  1.0; 
  k_atp	=  1.0; 
  k_cr	=  1.0; 
  k_p	=  1.0; 
  k_pcr	=  1.0; 
  rt	=  1.0; 
  k_adk	=  1.0; 
  k_ck	=  1.0; 
  rho_adk	=  1.0; 
  rho_ck	=  1.0; 
  v_adk	=  1.0; 
  v_ck	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_adp;
  mttpar(2)	= k_amp;
  mttpar(3)	= k_atp;
  mttpar(4)	= k_cr;
  mttpar(5)	= k_p;
  mttpar(6)	= k_pcr;
  mttpar(7)	= rt;
  mttpar(8)	= k_adk;
  mttpar(9)	= k_ck;
  mttpar(10)	= rho_adk;
  mttpar(11)	= rho_ck;
  mttpar(12)	= v_adk;
  mttpar(13)	= v_ck;
## END Code
endfunction
