
function [mttpar] = iGAP2LAC_numpar;
## [mttpar] = iGAP2LAC_numpar;
## System iGAP2LAC, representation numpar, language m; 
## File iGAP2LAC_numpar.m; 
## Generated by MTT on Thu Jan 29 13:20:52 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(31,1);

## BEGIN Code

## User defined code from iGAP2LAC_numpar.txt
  k_dpg	=  1.0; 
  k_lac	=  1.0; 
  k_laco	=  1.0; 
  k_nad	=  1.0; 
  k_nadh	=  1.0; 
  k_p2g	=  1.0; 
  k_p3g	=  1.0; 
  k_pep	=  1.0; 
  k_pyr	=  1.0; 
  rt	=  1.0; 
  k_eno	=  1.0; 
  k_fout	=  1.0; 
  k_gapdh	=  1.0; 
  k_ldh	=  1.0; 
  k_pgk	=  1.0; 
  k_pgm	=  1.0; 
  k_pk	=  1.0; 
  rho_eno	=  1.0; 
  rho_fout	=  1.0; 
  rho_gapdh	=  1.0; 
  rho_ldh	=  1.0; 
  rho_pgk	=  1.0; 
  rho_pgm	=  1.0; 
  rho_pk	=  1.0; 
  v_eno	=  1.0; 
  v_fout	=  1.0; 
  v_gapdh	=  1.0; 
  v_ldh	=  1.0; 
  v_pgk	=  1.0; 
  v_pgm	=  1.0; 
  v_pk	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_dpg;
  mttpar(2)	= k_lac;
  mttpar(3)	= k_laco;
  mttpar(4)	= k_nad;
  mttpar(5)	= k_nadh;
  mttpar(6)	= k_p2g;
  mttpar(7)	= k_p3g;
  mttpar(8)	= k_pep;
  mttpar(9)	= k_pyr;
  mttpar(10)	= rt;
  mttpar(11)	= k_eno;
  mttpar(12)	= k_fout;
  mttpar(13)	= k_gapdh;
  mttpar(14)	= k_ldh;
  mttpar(15)	= k_pgk;
  mttpar(16)	= k_pgm;
  mttpar(17)	= k_pk;
  mttpar(18)	= rho_eno;
  mttpar(19)	= rho_fout;
  mttpar(20)	= rho_gapdh;
  mttpar(21)	= rho_ldh;
  mttpar(22)	= rho_pgk;
  mttpar(23)	= rho_pgm;
  mttpar(24)	= rho_pk;
  mttpar(25)	= v_eno;
  mttpar(26)	= v_fout;
  mttpar(27)	= v_gapdh;
  mttpar(28)	= v_ldh;
  mttpar(29)	= v_pgk;
  mttpar(30)	= v_pgm;
  mttpar(31)	= v_pk;
## END Code
endfunction
