
function [mttpar] = iGLY2FBP_numpar;
## [mttpar] = iGLY2FBP_numpar;
## System iGLY2FBP, representation numpar, language m; 
## File iGLY2FBP_numpar.m; 
## Generated by MTT on Thu Jan 29 13:19:57 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(20,1);

## BEGIN Code

## User defined code from iGLY2FBP_numpar.txt
  k_f6p	=  1.0; 
  k_g1p	=  1.0; 
  k_g6p	=  1.0; 
  k_gly	=  1.0; 
  rt	=  1.0; 
  k_gpa	=  1.0; 
  k_gpb	=  1.0; 
  k_pfk	=  1.0; 
  k_pgi	=  1.0; 
  k_pglm	=  1.0; 
  rho_gpa	=  1.0; 
  rho_gpb	=  1.0; 
  rho_pfk	=  1.0; 
  rho_pgi	=  1.0; 
  rho_pglm	=  1.0; 
  v_gpa	=  1.0; 
  v_gpb	=  1.0; 
  v_pfk	=  1.0; 
  v_pgi	=  1.0; 
  v_pglm	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_f6p;
  mttpar(2)	= k_g1p;
  mttpar(3)	= k_g6p;
  mttpar(4)	= k_gly;
  mttpar(5)	= rt;
  mttpar(6)	= k_gpa;
  mttpar(7)	= k_gpb;
  mttpar(8)	= k_pfk;
  mttpar(9)	= k_pgi;
  mttpar(10)	= k_pglm;
  mttpar(11)	= rho_gpa;
  mttpar(12)	= rho_gpb;
  mttpar(13)	= rho_pfk;
  mttpar(14)	= rho_pgi;
  mttpar(15)	= rho_pglm;
  mttpar(16)	= v_gpa;
  mttpar(17)	= v_gpb;
  mttpar(18)	= v_pfk;
  mttpar(19)	= v_pgi;
  mttpar(20)	= v_pglm;
## END Code
endfunction
