
function [mttpar] = LAC_numpar;
## [mttpar] = LAC_numpar;
## System LAC, representation numpar, language m; 
## File LAC_numpar.m; 
## Generated by MTT on Wed Jan 14 13:57:51 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(17,1);

## BEGIN Code

## User defined code from LAC_numpar.txt
  k_lac	=  1.0; 
  k_laco	=  1.0; 
  k_pep	=  1.0; 
  k_pyr	=  1.0; 
  rt	=  1.0; 
  k_eno	=  1.0; 
  k_fout	=  1.0; 
  k_ldh	=  1.0; 
  k_pk	=  1.0; 
  rho_eno	=  1.0; 
  rho_fout	=  1.0; 
  rho_ldh	=  1.0; 
  rho_pk	=  1.0; 
  v_eno	=  1.0; 
  v_fout	=  1.0; 
  v_ldh	=  1.0; 
  v_pk	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_lac;
  mttpar(2)	= k_laco;
  mttpar(3)	= k_pep;
  mttpar(4)	= k_pyr;
  mttpar(5)	= rt;
  mttpar(6)	= k_eno;
  mttpar(7)	= k_fout;
  mttpar(8)	= k_ldh;
  mttpar(9)	= k_pk;
  mttpar(10)	= rho_eno;
  mttpar(11)	= rho_fout;
  mttpar(12)	= rho_ldh;
  mttpar(13)	= rho_pk;
  mttpar(14)	= v_eno;
  mttpar(15)	= v_fout;
  mttpar(16)	= v_ldh;
  mttpar(17)	= v_pk;
## END Code
endfunction
