
function [mttu] = LamKus02_input(mttx,mtty,mttt,mttpar);
## [mttu] = LamKus02_input(mttx,mtty,mttt,mttpar);
## System LamKus02, representation input, language m; 
## File LamKus02_input.m; 
## Generated by MTT on Mon Mar  2 14:55:39 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_adp 	= mttpar(1);
   k_amp 	= mttpar(2);
   k_atp 	= mttpar(3);
   k_cr 	= mttpar(4);
   k_dhap 	= mttpar(5);
   k_dpg 	= mttpar(6);
   k_f6p 	= mttpar(7);
   k_fbp 	= mttpar(8);
   k_g1p 	= mttpar(9);
   k_g6p 	= mttpar(10);
   k_gap 	= mttpar(11);
   k_gly 	= mttpar(12);
   k_lac 	= mttpar(13);
   k_laco 	= mttpar(14);
   k_nad 	= mttpar(15);
   k_nadh 	= mttpar(16);
   k_p 	= mttpar(17);
   k_p2g 	= mttpar(18);
   k_p3g 	= mttpar(19);
   k_pcr 	= mttpar(20);
   k_pep 	= mttpar(21);
   k_pyr 	= mttpar(22);
   rt 	= mttpar(23);
   k_adk 	= mttpar(24);
   k_ald 	= mttpar(25);
   k_atpase 	= mttpar(26);
   k_ck 	= mttpar(27);
   k_eno 	= mttpar(28);
   k_fout 	= mttpar(29);
   k_gapdh 	= mttpar(30);
   k_gpa 	= mttpar(31);
   k_gpb 	= mttpar(32);
   k_ldh 	= mttpar(33);
   k_pfk 	= mttpar(34);
   k_pgi 	= mttpar(35);
   k_pgk 	= mttpar(36);
   k_pglm 	= mttpar(37);
   k_pgm 	= mttpar(38);
   k_pk 	= mttpar(39);
   k_tpi 	= mttpar(40);
   rho_adk 	= mttpar(41);
   rho_ald 	= mttpar(42);
   rho_atpase 	= mttpar(43);
   rho_ck 	= mttpar(44);
   rho_eno 	= mttpar(45);
   rho_fout 	= mttpar(46);
   rho_gapdh 	= mttpar(47);
   rho_gpa 	= mttpar(48);
   rho_gpb 	= mttpar(49);
   rho_ldh 	= mttpar(50);
   rho_pfk 	= mttpar(51);
   rho_pgi 	= mttpar(52);
   rho_pgk 	= mttpar(53);
   rho_pglm 	= mttpar(54);
   rho_pgm 	= mttpar(55);
   rho_pk 	= mttpar(56);
   rho_tpi 	= mttpar(57);
   v_adk 	= mttpar(58);
   v_ald 	= mttpar(59);
   v_atpase 	= mttpar(60);
   v_ck 	= mttpar(61);
   v_eno 	= mttpar(62);
   v_fout 	= mttpar(63);
   v_gapdh 	= mttpar(64);
   v_gpa 	= mttpar(65);
   v_gpb 	= mttpar(66);
   v_ldh 	= mttpar(67);
   v_pfk 	= mttpar(68);
   v_pgi 	= mttpar(69);
   v_pgk 	= mttpar(70);
   v_pglm 	= mttpar(71);
   v_pgm 	= mttpar(72);
   v_pk 	= mttpar(73);
   v_tpi 	= mttpar(74);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;
mttx6 = mttx(6) ;
mttx7 = mttx(7) ;
mttx8 = mttx(8) ;
mttx9 = mttx(9) ;
mttx10 = mttx(10) ;
mttx11 = mttx(11) ;
mttx12 = mttx(12) ;
mttx13 = mttx(13) ;
mttx14 = mttx(14) ;
mttx15 = mttx(15) ;
mttx16 = mttx(16) ;
mttx17 = mttx(17) ;
mttx18 = mttx(18) ;
mttx19 = mttx(19) ;
mttx20 = mttx(20) ;
mttx21 = mttx(21) ;
mttx22 = mttx(22) ;

   mttu = zeros(17,1);

## BEGIN Code

## States
  lamkus02__mttcramp__adp 	= mttx(1);
  lamkus02__mttcramp__amp 	= mttx(2);
  lamkus02__mttcramp__atp 	= mttx(3);
  lamkus02__mttcramp__cr 	= mttx(4);
  lamkus02__mttcramp__p 	= mttx(5);
  lamkus02__mttcramp__pcr 	= mttx(6);
  lamkus02__mttgly2lac__mttfbp2gap__dhap 	= mttx(7);
  lamkus02__mttgly2lac__mttfbp2gap__fbp 	= mttx(8);
  lamkus02__mttgly2lac__mttfbp2gap__gap 	= mttx(9);
  lamkus02__mttgly2lac__mttgap2lac__dpg 	= mttx(10);
  lamkus02__mttgly2lac__mttgap2lac__lac 	= mttx(11);
  lamkus02__mttgly2lac__mttgap2lac__laco 	= mttx(12);
  lamkus02__mttgly2lac__mttgap2lac__nad 	= mttx(13);
  lamkus02__mttgly2lac__mttgap2lac__nadh 	= mttx(14);
  lamkus02__mttgly2lac__mttgap2lac__p2g 	= mttx(15);
  lamkus02__mttgly2lac__mttgap2lac__p3g 	= mttx(16);
  lamkus02__mttgly2lac__mttgap2lac__pep 	= mttx(17);
  lamkus02__mttgly2lac__mttgap2lac__pyr 	= mttx(18);
  lamkus02__mttgly2lac__mttgly2fbp__f6p 	= mttx(19);
  lamkus02__mttgly2lac__mttgly2fbp__g1p 	= mttx(20);
  lamkus02__mttgly2lac__mttgly2fbp__g6p 	= mttx(21);
  lamkus02__mttgly2lac__mttgly2fbp__gly 	= mttx(22);

## User defined code from LamKus02_input.txt
  lamkus02__atpase__v_1__u	=  1.0; 
  lamkus02__mttcramp__adk__v_1__u	=  1.0; 
  lamkus02__mttcramp__ck__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttfbp2gap__ald__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttfbp2gap__tpi__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgap2lac__eno__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgap2lac__fout__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgap2lac__gapdh__re__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgap2lac__ldh__re__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgap2lac__pgk__re__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgap2lac__pgm__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgap2lac__pk__re__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgly2fbp__gp__gpa__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgly2fbp__gp__gpb__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgly2fbp__pfk__re__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgly2fbp__pgi__v_1__u	=  1.0; 
  lamkus02__mttgly2lac__mttgly2fbp__pglm__v_1__u	=  1.0; 

  ## Set up the mttu vector
  mttu(1)	= lamkus02__mttcramp__adk__v_1__u;
  mttu(2)	= lamkus02__mttcramp__ck__v_1__u;
  mttu(3)	= lamkus02__mttgly2lac__mttfbp2gap__ald__v_1__u;
  mttu(4)	= lamkus02__mttgly2lac__mttfbp2gap__tpi__v_1__u;
  mttu(5)	= lamkus02__mttgly2lac__mttgap2lac__eno__v_1__u;
  mttu(6)	= lamkus02__mttgly2lac__mttgap2lac__fout__v_1__u;
  mttu(7)	= lamkus02__mttgly2lac__mttgap2lac__pgm__v_1__u;
  mttu(8)	= lamkus02__mttgly2lac__mttgap2lac__gapdh__re__v_1__u;
  mttu(9)	= lamkus02__mttgly2lac__mttgap2lac__ldh__re__v_1__u;
  mttu(10)	= lamkus02__mttgly2lac__mttgap2lac__pgk__re__v_1__u;
  mttu(11)	= lamkus02__mttgly2lac__mttgap2lac__pk__re__v_1__u;
  mttu(12)	= lamkus02__mttgly2lac__mttgly2fbp__gp__gpa__v_1__u;
  mttu(13)	= lamkus02__mttgly2lac__mttgly2fbp__gp__gpb__v_1__u;
  mttu(14)	= lamkus02__mttgly2lac__mttgly2fbp__pgi__v_1__u;
  mttu(15)	= lamkus02__mttgly2lac__mttgly2fbp__pglm__v_1__u;
  mttu(16)	= lamkus02__mttgly2lac__mttgly2fbp__pfk__re__v_1__u;
  mttu(17)	= lamkus02__atpase__v_1__u;
## END Code
endfunction
