
function [mttpar] = PG_numpar;
## [mttpar] = PG_numpar;
## System PG, representation numpar, language m; 
## File PG_numpar.m; 
## Generated by MTT on Wed Jan 14 13:57:22 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(25,1);

## BEGIN Code

## User defined code from PG_numpar.txt
  k_dhap	=  1.0; 
  k_dpg	=  1.0; 
  k_fdp	=  1.0; 
  k_gap	=  1.0; 
  k_p2g	=  1.0; 
  k_p3g	=  1.0; 
  rt	=  1.0; 
  k_ald	=  1.0; 
  k_gapdh	=  1.0; 
  k_pfk	=  1.0; 
  k_pgk	=  1.0; 
  k_pgm	=  1.0; 
  k_tpi	=  1.0; 
  rho_ald	=  1.0; 
  rho_gapdh	=  1.0; 
  rho_pfk	=  1.0; 
  rho_pgk	=  1.0; 
  rho_pgm	=  1.0; 
  rho_tpi	=  1.0; 
  v_ald	=  1.0; 
  v_gapdh	=  1.0; 
  v_pfk	=  1.0; 
  v_pgk	=  1.0; 
  v_pgm	=  1.0; 
  v_tpi	=  1.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_dhap;
  mttpar(2)	= k_dpg;
  mttpar(3)	= k_fdp;
  mttpar(4)	= k_gap;
  mttpar(5)	= k_p2g;
  mttpar(6)	= k_p3g;
  mttpar(7)	= rt;
  mttpar(8)	= k_ald;
  mttpar(9)	= k_gapdh;
  mttpar(10)	= k_pfk;
  mttpar(11)	= k_pgk;
  mttpar(12)	= k_pgm;
  mttpar(13)	= k_tpi;
  mttpar(14)	= rho_ald;
  mttpar(15)	= rho_gapdh;
  mttpar(16)	= rho_pfk;
  mttpar(17)	= rho_pgk;
  mttpar(18)	= rho_pgm;
  mttpar(19)	= rho_tpi;
  mttpar(20)	= v_ald;
  mttpar(21)	= v_gapdh;
  mttpar(22)	= v_pfk;
  mttpar(23)	= v_pgk;
  mttpar(24)	= v_pgm;
  mttpar(25)	= v_tpi;
## END Code
endfunction
