function sympar = ABCAv_sympar();
% sympar = ABCAv_sympar();
%System ABCAv, representation sympar, language m;
%File ABCAv_sympar.m;
%Generated by MTT on Mon Mar  2 14:50:42 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_a 	= 1; # ABCAv
  sympar.K_b 	= 2; # ABCAv
  sympar.K_c 	= 3; # ABCAv
  sympar.RT 	= 4; # ABCAv
  sympar.kappa_1 	= 5; # ABCAv
  sympar.kappa_2 	= 6; # ABCAv
  sympar.kappa_3 	= 7; # ABCAv
  sympar.v_e 	= 8; # ABCAv
