function [input_name,output_name,state_name,nonstate_name] = ABCAo_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = ABCAo_struc
%% Structure file (ABCAo_struc.m)
%% Generated by MTT at Mon Mar  2 14:49:34 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'ABCAo__r1__v_1__u_u'
'ABCAo__r2__v_1__u_u'
'ABCAo__r3__v_1__u_u'
];
output_name = [
'ABCAo__r1__v_2__y_y'
'ABCAo__r2__v_2__y_y'
'ABCAo__r3__v_2__y_y'
];
state_name = [
'ABCAo__A_A'
'ABCAo__B_B'
'ABCAo__C_C'
];
