function [input_name,output_name,state_name,nonstate_name] = ABCAoC_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = ABCAoC_struc
%% Structure file (ABCAoC_struc.m)
%% Generated by MTT at Mon Mar  2 14:51:12 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'ABCAoC__r1__v_1__u_u'
'ABCAoC__r2__v_1__u_u'
'ABCAoC__r3__v_1__u_u'
];
output_name = [
'ABCAoC__r1__v_2__y_y'
'ABCAoC__r2__v_2__y_y'
'ABCAoC__r3__v_2__y_y'
];
state_name = [
'ABCAoC__A_A'
'ABCAoC__B_B'
'ABCAoC__C_C'
'ABCAoC__F_F'
'ABCAoC__R_R'
];
