
function [mtty] = ABCA_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ABCA_odeo(mttx,mttu,mttt,mttpar);
## System ABCA, representation odeo, language m; 
## File ABCA_odeo.m; 
## Generated by MTT on Mon Mar  2 14:48:40 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   rt 	= mttpar(4);
   kappa_1 	= mttpar(5);
   kappa_2 	= mttpar(6);
   kappa_3 	= mttpar(7);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);

## Unknown Inputs 

   mtty = zeros(3,1);

## BEGIN Code

## Code
  mtty(1) = kappa_1*(k_a*mttx1 - k_b*mttx2);
  mtty(2) = kappa_2*(k_b*mttx2 - k_c*mttx3);
  mtty(3) = kappa_3*( - k_a*mttx1 + k_c*mttx3);
## END Code
endfunction
