
function [mttpar] = ABCA_numpar;
## [mttpar] = ABCA_numpar;
## System ABCA, representation numpar, language m; 
## File ABCA_numpar.m; 
## Generated by MTT on Mon Mar  2 14:48:38 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(7,1);

## BEGIN Code

## User defined code from ABCA_numpar.txt
  k_a	=  1.0; 
  k_b	=  1.0; 
  k_c	=  2.0; 
  rt	=  1.0; 
  kappa_1	=  1; 
  kappa_2	=  2; 
  kappa_3	=  3; 

  ## Set up the mttpar vector
  mttpar(1)	= k_a;
  mttpar(2)	= k_b;
  mttpar(3)	= k_c;
  mttpar(4)	= rt;
  mttpar(5)	= kappa_1;
  mttpar(6)	= kappa_2;
  mttpar(7)	= kappa_3;
## END Code
endfunction
