
function [mttu] = ABCAv_input(mttx,mtty,mttt,mttpar);
## [mttu] = ABCAv_input(mttx,mtty,mttt,mttpar);
## System ABCAv, representation input, language m; 
## File ABCAv_input.m; 
## Generated by MTT on Mon Mar  2 14:50:43 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   rt 	= mttpar(4);
   kappa_1 	= mttpar(5);
   kappa_2 	= mttpar(6);
   kappa_3 	= mttpar(7);
   v_e 	= mttpar(8);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

   mttu = zeros(3,1);

## BEGIN Code

## States
  abcav__a 	= mttx(1);
  abcav__b 	= mttx(2);
  abcav__c 	= mttx(3);

## User defined code from ABCAv_input.txt
  abcav__r1__v_1__u	=  1.0; 
  abcav__r2__v_1__u	=  1.0; 
  abcav__r3__v_1__u	=  1.0; 

  ## Set up the mttu vector
  mttu(1)	= abcav__r1__v_1__u;
  mttu(2)	= abcav__r2__v_1__u;
  mttu(3)	= abcav__r3__v_1__u;
## END Code
endfunction
