
function [mtta,mttb,mttc,mttd,mtte] = ABCAoC_dm(mttpar,mttx);
## [mtta,mttb,mttc,mttd,mtte] = ABCAoC_dm(mttpar,mttx);
## System ABCAoC, representation dm, language m; 
## File ABCAoC_dm.m; 
## Generated by MTT on Mon Mar  2 14:51:11 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   k_f 	= mttpar(4);
   k_r 	= mttpar(5);
   rt 	= mttpar(6);
   kappa_1 	= mttpar(7);
   kappa_2 	= mttpar(8);
   kappa_3 	= mttpar(9);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;

   mtta = zeros(5,5);
   mttb = zeros(5,3);
   mttc = zeros(3,5);
   mttd = zeros(3,3);
   mtte = zeros(5,5);

## BEGIN Code

## Code
  mtte(1,1) = 1;
  mtte(2,2) = 1;
  mtte(3,3) = 1;
  mtte(4,4) = 1;
  mtte(5,5) = 1;
  mttb(1,1) = -1;
  mttb(1,3) = 1;
  mttb(2,1) = 1;
  mttb(2,2) = -1;
  mttb(3,2) = 1;
  mttb(3,3) = -1;
  mttb(4,3) = -1;
  mttb(5,3) = 1;
  mttc(1,1) = k_a*kappa_1;
  mttc(1,2) = - k_b*kappa_1;
  mttc(2,2) = k_b*kappa_2;
  mttc(2,3) = - k_c*kappa_2;
  mttc(3,1) = - k_a*k_r*kappa_3*mttx5;
  mttc(3,3) = k_c*k_f*kappa_3*mttx4;
  mttc(3,4) = k_c*k_f*kappa_3*mttx3;
  mttc(3,5) = - k_a*k_r*kappa_3*mttx1;
## END Code
endfunction
