
function [mtty] = ABCAovCon_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ABCAovCon_odeo(mttx,mttu,mttt,mttpar);
## System ABCAovCon, representation odeo, language m; 
## File ABCAovCon_odeo.m; 
## Generated by MTT on Thu Oct  9 11:41:02 EST 2014; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   k_d 	= mttpar(4);
   k_e 	= mttpar(5);
   rt 	= mttpar(6);
   kappa_1 	= mttpar(7);
   kappa_2 	= mttpar(8);
   kappa_3 	= mttpar(9);
   kappa_c 	= mttpar(10);
   w 	= mttpar(11);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);
mttu4 = mttu(4);

## Unknown Inputs 

   mtty = zeros(4,1);

## BEGIN Code

## Code
  mtty(1) = kappa_1*(k_a*mttx1 - k_b*mttx2);
  mtty(2) = kappa_2*(k_b*mttx2 - k_c*mttx3);
  mtty(3) = kappa_3*( - k_a*k_e*mttx1*mttx5 + k_c*k_d*mttx3*mttx4);
  mtty(4) = (kappa_c*( - k_d*mttx4 + k_e*mttx5*w))/(k_e*mttx5);
## END Code
endfunction
