function sympar = ABCA_sympar();
% sympar = ABCA_sympar();
%System ABCA, representation sympar, language m;
%File ABCA_sympar.m;
%Generated by MTT on Mon Mar  2 14:48:39 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_a 	= 1; # ABCA
  sympar.K_b 	= 2; # ABCA
  sympar.K_c 	= 3; # ABCA
  sympar.RT 	= 4; # ABCA
  sympar.kappa_1 	= 5; # ABCA
  sympar.kappa_2 	= 6; # ABCA
  sympar.kappa_3 	= 7; # ABCA
