function [input_name,output_name,state_name,nonstate_name] = ABCAv_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = ABCAv_struc
%% Structure file (ABCAv_struc.m)
%% Generated by MTT at Mon Mar  2 14:50:42 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'ABCAv__r1__v_1__u_u'
'ABCAv__r2__v_1__u_u'
'ABCAv__r3__v_1__u_u'
];
output_name = [
'ABCAv__r1__v_2__y_y'
'ABCAv__r2__v_2__y_y'
'ABCAv__r3__v_2__y_y'
];
state_name = [
'ABCAv__A_A'
'ABCAv__B_B'
'ABCAv__C_C'
];
