
function [mtty] = ABCAoC_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ABCAoC_odeo(mttx,mttu,mttt,mttpar);
## System ABCAoC, representation odeo, language m; 
## File ABCAoC_odeo.m; 
## Generated by MTT on Mon Mar  2 14:51:12 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   k_f 	= mttpar(4);
   k_r 	= mttpar(5);
   rt 	= mttpar(6);
   kappa_1 	= mttpar(7);
   kappa_2 	= mttpar(8);
   kappa_3 	= mttpar(9);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;
mttx4 = mttx(4) ;
mttx5 = mttx(5) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);

## Unknown Inputs 

   mtty = zeros(3,1);

## BEGIN Code

## Code
  mtty(1) = kappa_1*(k_a*mttx1 - k_b*mttx2);
  mtty(2) = kappa_2*(k_b*mttx2 - k_c*mttx3);
  mtty(3) = kappa_3*( - k_a*k_r*mttx1*mttx5 + k_c*k_f*mttx3*mttx4);
## END Code
endfunction
