function sympar = ABCAo_sympar();
% sympar = ABCAo_sympar();
%System ABCAo, representation sympar, language m;
%File ABCAo_sympar.m;
%Generated by MTT on Mon Mar  2 14:49:34 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_a 	= 1; # ABCAo
  sympar.K_b 	= 2; # ABCAo
  sympar.K_c 	= 3; # ABCAo
  sympar.K_f 	= 4; # ABCAo
  sympar.K_r 	= 5; # ABCAo
  sympar.RT 	= 6; # ABCAo
  sympar.X_f 	= 7; # ABCAo
  sympar.X_r 	= 8; # ABCAo
  sympar.kappa_1 	= 9; # ABCAo
  sympar.kappa_2 	= 10; # ABCAo
  sympar.kappa_3 	= 11; # ABCAo
