
function [mttpar] = ABCADM_numpar;
## [mttpar] = ABCADM_numpar;
## System ABCADM, representation numpar, language m; 
## File ABCADM_numpar.m; 
## Generated by MTT on Mon Dec 29 09:08:11 AEDT 2014; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(13,1);

## BEGIN Code

## User defined code from ABCADM_numpar.txt
  k_a	=  1.0; 
  k_b	=  1.0; 
  k_c	=  2.0; 
  rt	=  1.0; 
  k_v1	=  1;
  k_v2	=  1;
  k_v3	=  1;
  rho_1	=  0.5;
  rho_2	=  0.5;
  rho_3	=  0.5;
  v_m1	=  1;
  v_m2	=  1;
  v_m3	=  1;

  ## Set up the mttpar vector
  mttpar(1)	= k_a;
  mttpar(2)	= k_b;
  mttpar(3)	= k_c;
  mttpar(4)	= rt;
  mttpar(5)	= k_v1;
  mttpar(6)	= k_v2;
  mttpar(7)	= k_v3;
  mttpar(8)	= rho_1;
  mttpar(9)	= rho_2;
  mttpar(10)	= rho_3;
  mttpar(11)	= v_m1;
  mttpar(12)	= v_m2;
  mttpar(13)	= v_m3;
## END Code
endfunction
