
function [mttu] = ABCAo_input(mttx,mtty,mttt,mttpar);
## [mttu] = ABCAo_input(mttx,mtty,mttt,mttpar);
## System ABCAo, representation input, language m; 
## File ABCAo_input.m; 
## Generated by MTT on Mon Mar  2 14:49:35 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   k_f 	= mttpar(4);
   k_r 	= mttpar(5);
   rt 	= mttpar(6);
   x_f 	= mttpar(7);
   x_r 	= mttpar(8);
   kappa_1 	= mttpar(9);
   kappa_2 	= mttpar(10);
   kappa_3 	= mttpar(11);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

   mttu = zeros(3,1);

## BEGIN Code

## States
  abcao__a 	= mttx(1);
  abcao__b 	= mttx(2);
  abcao__c 	= mttx(3);

## User defined code from ABCAo_input.txt
  abcao__r1__v_1__u	=  1.0; 
  abcao__r2__v_1__u	=  1.0; 
  abcao__r3__v_1__u	=  1.0; 

  ## Set up the mttu vector
  mttu(1)	= abcao__r1__v_1__u;
  mttu(2)	= abcao__r2__v_1__u;
  mttu(3)	= abcao__r3__v_1__u;
## END Code
endfunction
