% Steady-state parameter file (ABCAo_sspar.r)
% Generated by MTT at Tue Apr 29 08:18:03 EST 2014

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id: rcs_header.m,v 1.1 2000/12/28 09:32:04 peterg Exp $
% % $Log: rcs_header.m,v $
% % Revision 1.1  2000/12/28 09:32:04  peterg
% % Initial revision
% %
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% Steady-state states
%%MTTX1 := 	0; % ABCAo__A (A)
% Steady-state inputs
%%MTTU1 := 	0; % ABCAo__in (in)
%%MTTU2 := 	0; % ABCAo__out (out)
;;END;
