function sympar = ABCAoC_sympar();
% sympar = ABCAoC_sympar();
%System ABCAoC, representation sympar, language m;
%File ABCAoC_sympar.m;
%Generated by MTT on Mon Mar  2 14:51:12 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_a 	= 1; # ABCAoC
  sympar.K_b 	= 2; # ABCAoC
  sympar.K_c 	= 3; # ABCAoC
  sympar.K_f 	= 4; # ABCAoC
  sympar.K_r 	= 5; # ABCAoC
  sympar.RT 	= 6; # ABCAoC
  sympar.kappa_1 	= 7; # ABCAoC
  sympar.kappa_2 	= 8; # ABCAoC
  sympar.kappa_3 	= 9; # ABCAoC
