
function [mtta,mttb,mttc,mttd,mtte] = ABCAv_dm(mttpar,mttx);
## [mtta,mttb,mttc,mttd,mtte] = ABCAv_dm(mttpar,mttx);
## System ABCAv, representation dm, language m; 
## File ABCAv_dm.m; 
## Generated by MTT on Mon Mar  2 14:50:02 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   rt 	= mttpar(4);
   kappa_1 	= mttpar(5);
   kappa_2 	= mttpar(6);
   kappa_3 	= mttpar(7);
   v_e 	= mttpar(8);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

   mtta = zeros(3,3);
   mttb = zeros(3,3);
   mttc = zeros(3,3);
   mttd = zeros(3,3);
   mtte = zeros(3,3);

## BEGIN Code

## Code
  mtte(1,1) = 1;
  mtte(2,2) = 1;
  mtte(3,3) = 1;
  mttb(1,1) = -1;
  mttb(1,3) = 1;
  mttb(2,1) = 1;
  mttb(2,2) = -1;
  mttb(3,2) = 1;
  mttb(3,3) = -1;
  mttc(1,1) = k_a*kappa_1;
  mttc(1,2) = - k_b*kappa_1;
  mttc(2,2) = k_b*kappa_2;
  mttc(2,3) = - k_c*kappa_2;
  mttc(3,1) = - k_a*kappa_3;
  mttc(3,3) = k_c*kappa_3;
## END Code
endfunction
