function [input_name,output_name,state_name,nonstate_name] = ABCA_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = ABCA_struc
%% Structure file (ABCA_struc.m)
%% Generated by MTT at Mon Mar  2 14:48:39 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'ABCA__r1__v_1__u_u'
'ABCA__r2__v_1__u_u'
'ABCA__r3__v_1__u_u'
];
output_name = [
'ABCA__r1__v_2__y_y'
'ABCA__r2__v_2__y_y'
'ABCA__r3__v_2__y_y'
];
state_name = [
'ABCA__A_A'
'ABCA__B_B'
'ABCA__C_C'
];
