
function [mtty] = ABCAok_odeo(mttx,mttu,mttt,mttpar);
## [mtty] = ABCAok_odeo(mttx,mttu,mttt,mttpar);
## System ABCAok, representation odeo, language m; 
## File ABCAok_odeo.m; 
## Generated by MTT on Sun Dec 28 11:36:45 AEDT 2014; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

## Parameters 
   k_a 	= mttpar(1);
   k_b 	= mttpar(2);
   k_c 	= mttpar(3);
   k_f 	= mttpar(4);
   k_r 	= mttpar(5);
   rt 	= mttpar(6);
   x_f 	= mttpar(7);
   x_r 	= mttpar(8);
   kappa_1 	= mttpar(9);
   kappa_2 	= mttpar(10);
   kappa_3 	= mttpar(11);

## States 
mttx1 = mttx(1) ;
mttx2 = mttx(2) ;
mttx3 = mttx(3) ;

## Inputs 
mttu1 = mttu(1);
mttu2 = mttu(2);
mttu3 = mttu(3);

## Unknown Inputs 

   mtty = zeros(3,1);

## BEGIN Code

## Code
  mtty(1) = kappa_1*(k_a*mttx1 - k_b*mttx2);
  mtty(2) = kappa_2*(k_b*mttx2 - k_c*mttx3);
  mtty(3) = kappa_3*( - k_a*k_r*mttx1*x_r + k_c*k_f*mttx3*x_f);
## END Code
endfunction
