
function [mttpar] = iABCAovCon_numpar;
## [mttpar] = iABCAovCon_numpar;
## System iABCAovCon, representation numpar, language m; 
## File iABCAovCon_numpar.m; 
## Generated by MTT on Thu Oct  9 11:41:00 EST 2014; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(11,1);

## BEGIN Code

## User defined code from iABCAovCon_numpar.txt
  k_a	=  1.0; 
  k_b	=  1.0; 
  k_c	=  1.0; 
  k_d	=  1.0; 
  k_e	=  1.0; 
  rt	=  1.0; 
  kappa_1	=  1.0; 
  kappa_2	=  1.0; 
  kappa_3	=  1.0; 
  kappa_c	=  10.0; 
  w	=  3.0; 

  ## Set up the mttpar vector
  mttpar(1)	= k_a;
  mttpar(2)	= k_b;
  mttpar(3)	= k_c;
  mttpar(4)	= k_d;
  mttpar(5)	= k_e;
  mttpar(6)	= rt;
  mttpar(7)	= kappa_1;
  mttpar(8)	= kappa_2;
  mttpar(9)	= kappa_3;
  mttpar(10)	= kappa_c;
  mttpar(11)	= w;
## END Code
endfunction
