function sympar = iABCAv_sympar();
% sympar = iABCAv_sympar();
%System iABCAv, representation sympar, language m;
%File iABCAv_sympar.m;
%Generated by MTT on Mon Mar  2 14:50:42 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_a 	= 1; # iABCAv
  sympar.K_b 	= 2; # iABCAv
  sympar.K_c 	= 3; # iABCAv
  sympar.RT 	= 4; # iABCAv
  sympar.kappa_1 	= 5; # iABCAv
  sympar.kappa_2 	= 6; # iABCAv
  sympar.kappa_3 	= 7; # iABCAv
