function [input_name,output_name,state_name,nonstate_name] = iABCAv_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = iABCAv_struc
%% Structure file (iABCAv_struc.m)
%% Generated by MTT at Mon Mar  2 14:50:43 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'iABCAv__r3__v_1__u_u'
'iABCAv__c__v_i__u_u'
];
nonstate_name = [
'iABCAv__B_B'
'iABCAv__C_C'
];
output_name = [
'iABCAv__r1__v_2__y_y'
'iABCAv__r2__v_2__y_y'
'iABCAv__r3__v_2__y_y'
'iABCAv__c__v__y_y'
];
state_name = [
'iABCAv__A_A'
];
