
function [mttpar] = iABCAo_numpar;
## [mttpar] = iABCAo_numpar;
## System iABCAo, representation numpar, language m; 
## File iABCAo_numpar.m; 
## Generated by MTT on Mon Mar  2 14:49:34 AEDT 2015; 

## Horrible fudge to make mtt_m2p work
global ...
mtt_no_globals ;

   mttpar = zeros(11,1);

## BEGIN Code

## User defined code from iABCAo_numpar.txt
  k_a	=  1;
  k_b	=  1;
  k_c	=  1;
  k_f	=  1;
  k_r	=  1;
  rt	=  1;
  kappa_1	=  1;
  kappa_2	=  1;
  kappa_3	=  1;
  x_f	=  2;
  x_r	=  1;

  ## Set up the mttpar vector
  mttpar(1)	= k_a;
  mttpar(2)	= k_b;
  mttpar(3)	= k_c;
  mttpar(4)	= k_f;
  mttpar(5)	= k_r;
  mttpar(6)	= rt;
  mttpar(7)	= x_f;
  mttpar(8)	= x_r;
  mttpar(9)	= kappa_1;
  mttpar(10)	= kappa_2;
  mttpar(11)	= kappa_3;
## END Code
endfunction
