function [input_name,output_name,state_name,nonstate_name] = iABCA_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = iABCA_struc
%% Structure file (iABCA_struc.m)
%% Generated by MTT at Mon Mar  2 14:48:39 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'iABCA__r3__v_1__u_u'
];
nonstate_name = [
'iABCA__A_A'
'iABCA__B_B'
];
output_name = [
'iABCA__r1__v_2__y_y'
'iABCA__r2__v_2__y_y'
'iABCA__r3__v_2__y_y'
];
state_name = [
'iABCA__C_C'
];
