function [input_name,output_name,state_name,nonstate_name] = iABCAo_struc
%% Usage: [input_name,output_name,state_name,nonstate_name] = iABCAo_struc
%% Structure file (iABCAo_struc.m)
%% Generated by MTT at Mon Mar  2 14:49:34 AEDT 2015

## Default to null strings
 input_name = "";
 output_name = "";
 state_name  = ""; 
 nonstate_name  = "";
input_name = [
'iABCAo__r3__v_1__u_u'
];
nonstate_name = [
'iABCAo__B_B'
'iABCAo__C_C'
];
output_name = [
'iABCAo__r1__v_2__y_y'
'iABCAo__r2__v_2__y_y'
'iABCAo__r3__v_2__y_y'
];
state_name = [
'iABCAo__A_A'
];
