function sympar = iABCA_sympar();
% sympar = iABCA_sympar();
%System iABCA, representation sympar, language m;
%File iABCA_sympar.m;
%Generated by MTT on Mon Mar  2 14:48:39 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_a 	= 1; # iABCA
  sympar.K_b 	= 2; # iABCA
  sympar.K_c 	= 3; # iABCA
  sympar.RT 	= 4; # iABCA
  sympar.kappa_1 	= 5; # iABCA
  sympar.kappa_2 	= 6; # iABCA
  sympar.kappa_3 	= 7; # iABCA
