function sympar = iABCAo_sympar();
% sympar = iABCAo_sympar();
%System iABCAo, representation sympar, language m;
%File iABCAo_sympar.m;
%Generated by MTT on Mon Mar  2 14:49:34 AEDT 2015;
%
global ...
mtt_no_globals ;
  sympar.K_a 	= 1; # iABCAo
  sympar.K_b 	= 2; # iABCAo
  sympar.K_c 	= 3; # iABCAo
  sympar.K_f 	= 4; # iABCAo
  sympar.K_r 	= 5; # iABCAo
  sympar.RT 	= 6; # iABCAo
  sympar.X_f 	= 7; # iABCAo
  sympar.X_r 	= 8; # iABCAo
  sympar.kappa_1 	= 9; # iABCAo
  sympar.kappa_2 	= 10; # iABCAo
  sympar.kappa_3 	= 11; # iABCAo
